title: "Conscientemente, atención psicológica"
description: "Espacio profesional dedicado a la psicoterapia, psicoeducación y bienestar emocional."
locale: "es-CO"

url: ""
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-include-cache

