# ===============================
# Configuración básica del sitio
# ===============================

title: "Conscientemente, atención psicológica"
logo: ""
subtitle: "Acompañamiento terapéutico con evidencia y calidez humana"
description: "Espacio profesional dedicado a la psicoterapia, psicoeducación y bienestar emocional."
locale: "es-CO"

# URL (por ahora usamos la de GitHub Pages)
url: ""
baseurl: ""

# ===============================
# Tema
# ===============================

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-include-cache
  - jekyll-paginate
paginate: 10
# ===============================
# Layout por defecto
# ===============================

defaults:
  - scope:
      path: "index.html"
    values:
      layout: default

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

# ===============================
# Navegación principal
# ===============================

navigation:
  main:
    - title: "Inicio"
      url: /
    - title: "Sobre mí"
      url: /sobre-mi/
    - title: "Servicios"
      url: /servicios/
    - title: "Contacto"
      url: /contacto/

      
  # rebuild
# ===============================
# Excepción para la página de inicio
# ===============================


